package main.java.token;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author victo
 */
public class TipoAtendimento extends javax.swing.JFrame {
static int senhaUrgencia = 1;
static int senhaEmergencia = 1;
static int senhaPreferencial = 1;
static int senhaPadrao = 1;

    /**
     * Creates new form TipoAtendimento
     */
    public TipoAtendimento() {
        super("TOKEN");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        urgBtn = new javax.swing.JButton();
        emerBtn = new javax.swing.JButton();
        prefBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cpfTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        padBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 113, 182));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        urgBtn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        urgBtn.setForeground(new java.awt.Color(0, 113, 182));
        urgBtn.setText("Urgência");
        urgBtn.setMaximumSize(new java.awt.Dimension(97, 23));
        urgBtn.setMinimumSize(new java.awt.Dimension(97, 23));
        urgBtn.setPreferredSize(new java.awt.Dimension(97, 23));
        urgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgBtnActionPerformed(evt);
            }
        });

        emerBtn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        emerBtn.setForeground(new java.awt.Color(0, 113, 182));
        emerBtn.setText("Emergência");
        emerBtn.setMaximumSize(new java.awt.Dimension(97, 23));
        emerBtn.setMinimumSize(new java.awt.Dimension(97, 23));
        emerBtn.setPreferredSize(new java.awt.Dimension(97, 23));
        emerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emerBtnActionPerformed(evt);
            }
        });

        prefBtn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        prefBtn.setForeground(new java.awt.Color(0, 113, 182));
        prefBtn.setText("Preferencial");
        prefBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/Imagens/aa.png"))); // NOI18N

        cpfTxt.setBackground(new java.awt.Color(0, 113, 182));
        cpfTxt.setForeground(new java.awt.Color(255, 255, 255));
        cpfTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPF:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        cpfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTxtActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ainda não tem seu cadastro?");

        jButton1.setText("Pré-Cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        padBtn.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        padBtn.setForeground(new java.awt.Color(0, 113, 182));
        padBtn.setText("Padrão");
        padBtn.setMaximumSize(new java.awt.Dimension(94, 22));
        padBtn.setMinimumSize(new java.awt.Dimension(94, 22));
        padBtn.setPreferredSize(new java.awt.Dimension(94, 22));
        padBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(prefBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(padBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cpfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefBtn)
                    .addComponent(urgBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(padBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgBtnActionPerformed
       
        try {
            DAO senhaU = new DAO();
            boolean a ;
      String cpf = cpfTxt.getText();

            a = senhaU.gerarFila(cpf);
            if(a){
             JOptionPane.showMessageDialog(null, "Senha: U" + senhaUrgencia++);
             this.dispose();
         
         }else{
             JOptionPane.showMessageDialog(null, "Usuário inválido!");
         }
        } catch (Exception ex) {
         JOptionPane.showMessageDialog(null, "Problemas Técnicos. Tente Novamente!");
        }

        this.dispose();
             
             TipoAtendimento token = new TipoAtendimento();
             token.setVisible(true);

    }//GEN-LAST:event_urgBtnActionPerformed

    private void emerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emerBtnActionPerformed
       try{
           DAO senhaE = new DAO();
           boolean a;
           String cpf = cpfTxt.getText();
           a = senhaE.gerarFila(cpf);
           
           if(a){
             JOptionPane.showMessageDialog(null, "Senha: E" + senhaEmergencia++);
             this.dispose();
         
         }else{
             JOptionPane.showMessageDialog(null, "Usuário inválido!");
         }
           
       }catch (Exception ex) {
         JOptionPane.showMessageDialog(null, "Problemas Técnicos. Tente Novamente!");
       }
       this.dispose();
             
             TipoAtendimento token = new TipoAtendimento();
             token.setVisible(true);
    }//GEN-LAST:event_emerBtnActionPerformed

    private void prefBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefBtnActionPerformed
         try{
           DAO senhaP = new DAO();
           boolean a;
           String cpf = cpfTxt.getText();
           a = senhaP.gerarFila(cpf);
           
           if(a){
             JOptionPane.showMessageDialog(null, "Senha: P" + senhaPreferencial++);
             this.dispose();
         
         }else{
             JOptionPane.showMessageDialog(null, "Usuário inválido!");
         }
           
       }catch (Exception ex) {
         JOptionPane.showMessageDialog(null, "Problemas Técnicos. Tente Novamente!");
       }
         this.dispose();
             
             TipoAtendimento token = new TipoAtendimento();
             token.setVisible(true);
    }//GEN-LAST:event_prefBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Cadastro Cframe = new Cadastro();
        Cframe.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cpfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTxtActionPerformed
        String cpf = cpfTxt.getText();
    }//GEN-LAST:event_cpfTxtActionPerformed

    private void padBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padBtnActionPerformed
         try{
           DAO senha = new DAO();
           boolean a;
           String cpf = cpfTxt.getText();
           a = senha.gerarFila(cpf);
           
           if(a){
             JOptionPane.showMessageDialog(null, "Senha: E" + senhaPadrao++);
             this.dispose();
         
         }else{
             JOptionPane.showMessageDialog(null, "Usuário inválido!");
         }
           
       }catch (Exception ex) {
         JOptionPane.showMessageDialog(null, "Problemas Técnicos. Tente Novamente!");
       }
         this.dispose();
             
             TipoAtendimento token = new TipoAtendimento();
             token.setVisible(true);
    }//GEN-LAST:event_padBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoAtendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfTxt;
    private javax.swing.JButton emerBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton padBtn;
    private javax.swing.JButton prefBtn;
    private javax.swing.JButton urgBtn;
    // End of variables declaration//GEN-END:variables
}
